// <auto-generated />
using System;
using Fatura.Infra.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fatura.Migrations
{
    [DbContext(typeof(EfSqliteAdapter))]
    partial class EfSqliteAdapterModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("Fatura.Domain.Models.TransacaoCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCompra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Moeda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCompra = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 0,
                            NumeroCartao = "1234",
                            Valor = 1200.0
                        },
                        new
                        {
                            Id = 2,
                            DataCompra = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 1,
                            NumeroCartao = "1234",
                            Valor = 400.0
                        },
                        new
                        {
                            Id = 3,
                            DataCompra = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 1,
                            NumeroCartao = "4321",
                            Valor = 400.0
                        },
                        new
                        {
                            Id = 4,
                            DataCompra = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 0,
                            NumeroCartao = "1234",
                            Valor = 200.0
                        },
                        new
                        {
                            Id = 5,
                            DataCompra = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 1,
                            NumeroCartao = "1234",
                            Valor = 50.0
                        },
                        new
                        {
                            Id = 6,
                            DataCompra = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoCompra = "",
                            Moeda = 1,
                            NumeroCartao = "4321",
                            Valor = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
